<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        body {
            font-family: 'Courier New', monospace;
            font-size: 11px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h2 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        table thead {
            background-color: #0070C0;
            color: white;
        }
        table th {
            border: 1px solid #999;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            font-size: 10px;
        }
        table td {
            border: 1px solid #ddd;
            padding: 8px;
            font-size: 10px;
        }
        table tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            margin-top: 20px;
            text-align: right;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>LAPORAN AR PERBULAN - SFINLOG</h2>
        <p>Tanggal Export: {{ now()->format('d-m-Y H:i:s') }}</p>
        @if($selectedMonth)
            <p>Bulan: {{ $selectedMonth }}</p>
        @else
            <p>Semua Data</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th class="text-center" width="4%">No.</th>
                <th class="text-center" width="10%">Periode</th>
                <th width="20%">Nama Debitur</th>
                <th class="text-right" width="11%">DEL 1-30</th>
                <th class="text-right" width="11%">DEL 31-60</th>
                <th class="text-right" width="11%">DEL 61-90</th>
                <th class="text-right" width="11%">NPL 91-179</th>
                <th class="text-right" width="12%">WRITE OFF >180</th>
                <th class="text-right" width="10%">Total AR</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $index => $row)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td class="text-center">{{ $row->periode ?? '-' }}</td>
                    <td>{{ $row->nama_debitur ?? '-' }}</td>
                    <td class="text-right">Rp {{ number_format($row->del_1_30 ?? 0, 0, ',', '.') }}</td>
                    <td class="text-right">Rp {{ number_format($row->del_31_60 ?? 0, 0, ',', '.') }}</td>
                    <td class="text-right">Rp {{ number_format($row->del_61_90 ?? 0, 0, ',', '.') }}</td>
                    <td class="text-right">Rp {{ number_format($row->npl_91_179 ?? 0, 0, ',', '.') }}</td>
                    <td class="text-right">Rp {{ number_format($row->write_off_180 ?? 0, 0, ',', '.') }}</td>
                    <td class="text-right"><strong>Rp {{ number_format(($row->del_1_30 ?? 0) + ($row->del_31_60 ?? 0) + ($row->del_61_90 ?? 0) + ($row->npl_91_179 ?? 0) + ($row->write_off_180 ?? 0), 0, ',', '.') }}</strong></td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" class="text-center">Tidak ada data</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by SYIFA System - {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
