<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        body {
            font-family: 'Courier New', monospace;
            font-size: 11px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h2 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        table thead {
            background-color: #0070C0;
            color: white;
        }
        table th {
            border: 1px solid #999;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        table td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        table tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            margin-top: 20px;
            text-align: right;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>LAPORAN AR PERBULAN</h2>
        <p>Tanggal Export: {{ now()->format('d-m-Y H:i:s') }}</p>
        @if($selectedMonth)
            <p>Bulan: {{ $selectedMonth }}</p>
        @else
            <p>Semua Data</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th class="text-center" width="5%">No.</th>
                <th width="12%">Bulan</th>
                <th width="30%">Nama Perusahaan</th>
                <th class="text-right" width="18%">Sisa AR Pokok</th>
                <th class="text-right" width="18%">Sisa Bagi Hasil</th>
                <th class="text-right" width="17%">Sisa AR Total</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $row)
                <tr>
                    <td class="text-center">{{ $row['no'] }}</td>
                    <td>{{ $row['bulan'] }}</td>
                    <td>{{ $row['nama_perusahaan'] }}</td>
                    <td class="text-right">Rp {{ number_format($row['sisa_ar_pokok'], 0, ',', '.') }}</td>
                    <td class="text-right">Rp {{ number_format($row['sisa_bagi_hasil'], 0, ',', '.') }}</td>
                    <td class="text-right"><strong>Rp {{ number_format($row['sisa_ar_total'], 0, ',', '.') }}</strong></td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="text-center">Tidak ada data</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by SYFA | {{ now()->format('d/m/Y') }}</p>
    </div>
</body>
</html>
